ifup: move most IPv6 configuration into DHCP exit hook

diff --git a/local-modules/eizo/templates/interfaces/ipv6-pd b/local-modules/eizo/templates/interfaces/ipv6-pd
--- a/local-modules/eizo/templates/interfaces/ipv6-pd
+++ b/local-modules/eizo/templates/interfaces/ipv6-pd
@@ -62,6 +62,22 @@ case $reason in
             fi
         done
     fi
+
+    # Site-specific: also handle default route
+    case $old_ip6_prefix,$new_ip6_prefix in
+      ,) : ;;
+      *,)
+        logger -t "dhcpv6-pd" -p daemon.info "remove default route"
+        sysctl -qw net.ipv6.conf.internet.accept_ra=0
+        ip -6 route del default || true
+        ;;
+      ,*)
+        logger -t "dhcpv6-pd" -p daemon.info "request default route"
+        sysctl -qw net.ipv6.conf.internet.accept_ra=2
+        rdisc6 internet || \
+            logger -t "dhcpv6-pd" -p daemon.err "cannot request default route"
+        ;;
+    esac
     ;;
 esac
 
